/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import java.awt.Font;

/**
 *
 * @author Gabriel
 */
public class TelaGenio extends javax.swing.JFrame {

    /**
     * Creates new form TelaGenio
     */
    public TelaGenio() {
        initComponents();
        lblFala.setText("<html>Vou pensar em um valor entre 1 e 5. Tente adivinhar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtValor = new javax.swing.JSpinner();
        btnBotao = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblFala = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        jLabel1.setText("Valor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        txtValor.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 56, 30));

        btnBotao.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        btnBotao.setForeground(new java.awt.Color(51, 51, 51));
        btnBotao.setText("Palpite");
        btnBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBotao, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 297, -1, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("./imagens/genio.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        lblFala.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        lblFala.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFala.setText("jLabel4");
        lblFala.setToolTipText("");
        lblFala.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblFala, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 34, 140, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("./imagens/balao.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 210, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBotaoActionPerformed
        // TODO add your handling code here:
        
        // Construindo o evento de aleatoriedade
        double ale = Math.random();
        int intervalo = (int) (1 + ale * (5-1));
        
        // Pegando o valor que o usuário inseriu
        int valor = Integer.parseInt(txtValor.getValue().toString());
        
        // Atribuindo as frases e comparando se o usuário acertou o valor
        String frase1 = "<html>ACERTOU";
        String frase2 = "<html>ERROOUU, EU PENSEI NO VALOR " + intervalo;
        
        lblFala.setFont(new Font("Arial Black", Font.PLAIN, 16));
        
        String resultado = (intervalo == valor) ? frase1 : frase2;
        
        
        // Exibindo o valor
        lblFala.setText(resultado);
        
        
        
    }//GEN-LAST:event_btnBotaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGenio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBotao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblFala;
    private javax.swing.JSpinner txtValor;
    // End of variables declaration//GEN-END:variables
}
